In [38]:
import numpy as np

In [39]:
np.random.seed(5)
populasyon = np.random.randint(0,80,1000)

In [40]:
populasyon[0:10]

array([78, 61, 16, 73,  8, 62, 27, 30,  7, 76])

In [41]:
#orneklem çekmek
np.random.seed(5)
orneklem=np.random.choice(a=populasyon,size=100)
orneklem[0:10]

array([71,  7, 53, 16, 71, 16,  7,  7, 53, 16])

random.seed() fonksiyonunda başlatacağımız bir başlangıç değeri yazdığımızda kod bloğunu çalıştırdığımızda her seferinde aynı çıktıları üretilir.

In [42]:
orneklem.mean()

40.42

Örnekleme ait ortalama ile populasyona ait ortalama değerler kıyaslandığında büyük bir farklılık olmadığını gözlemlemekteyiz.

In [43]:
populasyon.mean()

38.91

In [44]:
#orneklem dağılım

In [45]:
np.random.seed(5)
orneklem1 = np.random.choice(a=populasyon,size=100)
orneklem2 = np.random.choice(a=populasyon,size=100)
orneklem3 = np.random.choice(a=populasyon,size=100)
orneklem4 = np.random.choice(a=populasyon,size=100)
orneklem5 = np.random.choice(a=populasyon,size=100)
orneklem6 = np.random.choice(a=populasyon,size=100)
orneklem7 = np.random.choice(a=populasyon,size=100)
orneklem8 = np.random.choice(a=populasyon,size=100)
orneklem9 = np.random.choice(a=populasyon,size=100)
orneklem10 = np.random.choice(a=populasyon,size=100)
(orneklem1.mean()+orneklem1.mean()+orneklem2.mean()+orneklem3.mean()+orneklem4.mean()+orneklem5.mean()+orneklem6.mean()
 +orneklem7.mean()+orneklem8.mean()+orneklem9.mean()+orneklem10.mean())/10

44.084

Popülasyon içerisinden Seçtiğimiz on farklı örneklem yapılarının ortalamalarının ortalamasını gözlemleyebiliyoruz.

In [46]:
import seaborn as sns

In [47]:
tips=sns.load_dataset("tips")
df=tips.copy()
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [48]:
df.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [32]:
!pip install researchpy


[notice] A new release of pip is available: 23.3.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [33]:
import researchpy as rp

In [35]:
rp.summary_cont(df[["total_bill","tip","size"]])

C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\researchpy\summary.py:102: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'total_bill' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  table_a.iloc[0,0] = ix
C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\researchpy\summary.py:102: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'tip' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  table_a.iloc[0,0] = ix
C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\researchpy\summary.py:102: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'size' has dtype incompatible with float64, please explicitly cast to a compat

Variable      N     Mean      SD      SE  95% Conf.  Interval
0  total_bill  244.0  19.7859  8.9024  0.5699    18.6633   20.9086
1         tip  244.0   2.9983  1.3836  0.0886     2.8238    3.1728
2        size  244.0   2.5697  0.9511  0.0609     2.4497    2.6896

In [38]:
rp.summary_cat(df[["sex","smoker","day"]])

Variable Outcome  Count  Percent
0      sex    Male    157    64.34
1           Female     87    35.66
2   smoker      No    151    61.89
3              Yes     93    38.11
4      day     Sat     87    35.66
5              Sun     76    31.15
6             Thur     62    25.41
7              Fri     19     7.79

In [39]:
df[["tip","total_bill"]].cov()

tip  total_bill
tip         1.914455    8.323502
total_bill  8.323502   79.252939

In [50]:
df[["tip","total_bill"]].corr()

tip  total_bill
tip         1.000000    0.675734
total_bill  0.675734    1.000000

In [51]:
#iş uygulaması fiyat stratejisi Karar Destek //güven aralığı kullanılarak

In [52]:
import numpy as np
np.random.seed(5)
fiyatlar =np.random.randint(10,110,1000)

In [53]:
fiyatlar.mean()

58.143

In [83]:
import statsmodels.stats.api as sms

In [84]:
sms.DescrStatsW(fiyatlar).tconfint_mean(alpha=0.05)

(56.342303263549155, 59.943696736450846)

In [56]:
#Bernoulli Dağılımı

In [57]:
from scipy.stats import bernoulli

In [95]:
p = 0.3

In [96]:
rv = bernoulli(p)

In [98]:
rv.pmf(k=0)

0.7000000000000002

In [61]:
#Büyük Sayılar Yasası

In [62]:
import numpy as np
rng=np.random.RandomState(123)
for i in np.arange(1,21):
    deney_sayisi=2**i
    yazi_turalar=rng.randint(0,2, size=deney_sayisi)
    yazi_olasiliklari=np.mean(yazi_turalar)
    print("Atış Sayısı:",deney_sayisi,"-----",'Yazı Olasılığı %.2f'% (yazi_olasiliklari*100))

Atış Sayısı: 2 ----- Yazı Olasılığı 50.00
Atış Sayısı: 4 ----- Yazı Olasılığı 0.00
Atış Sayısı: 8 ----- Yazı Olasılığı 62.50
Atış Sayısı: 16 ----- Yazı Olasılığı 43.75
Atış Sayısı: 32 ----- Yazı Olasılığı 46.88
Atış Sayısı: 64 ----- Yazı Olasılığı 56.25
Atış Sayısı: 128 ----- Yazı Olasılığı 50.78
Atış Sayısı: 256 ----- Yazı Olasılığı 52.73
Atış Sayısı: 512 ----- Yazı Olasılığı 52.93
Atış Sayısı: 1024 ----- Yazı Olasılığı 50.20
Atış Sayısı: 2048 ----- Yazı Olasılığı 48.58
Atış Sayısı: 4096 ----- Yazı Olasılığı 49.49
Atış Sayısı: 8192 ----- Yazı Olasılığı 49.58
Atış Sayısı: 16384 ----- Yazı Olasılığı 49.96
Atış Sayısı: 32768 ----- Yazı Olasılığı 50.00
Atış Sayısı: 65536 ----- Yazı Olasılığı 49.68
Atış Sayısı: 131072 ----- Yazı Olasılığı 49.97
Atış Sayısı: 262144 ----- Yazı Olasılığı 50.13
Atış Sayısı: 524288 ----- Yazı Olasılığı 50.01
Atış Sayısı: 1048576 ----- Yazı Olasılığı 50.09


In [63]:
1/5

0.2

In [64]:
rng=np.random.RandomState(10)
yazi_turalar=rng.randint(0,2, size=20)
print(yazi_turalar)

[1 1 0 1 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0]


In [65]:
#Reklam Harcaması Optimizasyosunu

In [66]:
from scipy.stats import binom

In [112]:
p=0.05
n=500
rv=binom(n,p)
print(rv.pmf(1))
print(rv.pmf(5))
print(rv.pmf(10))
print(rv.pmf(20))

1.9143398845892622e-10
7.498792762520351e-07
0.00029165351975711865
0.051616192536641056


Poisson Dağılımı

In [100]:
from scipy.stats import poisson

In [113]:
lambda_ =0.2

In [114]:
rv=poisson(mu=lambda_)
print(rv.pmf(k=0))
print(rv.pmf(k=5))
print(rv.pmf(k=10))

0.8187307530779818
2.183282008207956e-06
2.3103513314369915e-14


Normal Dağılım

In [115]:
from scipy.stats import norm

In [120]:
1-norm.cdf(90,85,5)

0.15865525393145707

In [117]:
1-norm.cdf(70,80,5)

0.9772498680518208

In [118]:
norm.cdf(30,80,5)

7.61985302416047e-24

In [119]:
norm.cdf(90,80,5)-norm.cdf(85,80,5)

0.13590512198327787